language: python
python:
  - "2.7"
services:
  # - mongodb
  # - mysql
  # - rabbitmq
  # - memcached
  - docker
  
# env:
#   - TEST_SUITE="lms-unit"
#     SHARD=1
#   - TEST_SUITE="lms-unit"
#     SHARD=2
#   - TEST_SUITE="lms-unit"
#     SHARD=3
#   - TEST_SUITE="lms-unit"
#     SHARD=4
#   - TEST_SUITE="cms-unit"
#   - TEST_SUITE="lib"  
#   - TEST_SUITE="js-unit"
  
# cache:
#   pip: true
#   directories: node_modules

branches:
  only:
  - master
  - oxa/master.fic
  - oxa/dev.fic
  - oxa/ci
  - oxa/ci-docker

# command to install dependencies
# install: 

  
# before_script:
#   - "export PATH=$PATH:$PWD/node_modules/.bin"
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3

before_install:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker pull btelnes/devstack
  - docker run -d --name devstack --security-opt seccomp=unconfined --tmpfs /run --tmpfs /run/lock -v /sys/fs/cgroup:/sys/fs/cgroup:ro -t btelnes/devstack
  #- docker ps

# command to install dependencies
install:
  # Fix an issue caused by /var/lib/mongodb/mongod.lock (Exception in initAndListen: 12596 old lock file)
  - sudo -u mongodb mongod --repair --dbpath /var/lib/mongodb/
  - sudo service mongod start

# command to run tests
script: ./scripts/travis-tests.sh

addons:
  firefox: "45.0"
  chrome: stable

dist: trusty
