version: '2'

services:
  lms:
    command: bash -c 'source /edx/app/edxapp/edxapp_env && python /edx/app/edxapp/edx-platform/manage.py lms runserver 0.0.0.0:18000 --settings devstack_docker'
    container_name: edx.devstack.lms
    environment:
      NO_PYTHON_UNINSTALL: 1
    # image: edxops/edxapp:latest
    build: .
    network_mode: host
    ports:
      - "18000:18000"


  # studio:
  #   command: bash -c 'source /edx/app/edxapp/edxapp_env && python /edx/app/edxapp/edx-platform/manage.py cms runserver 0.0.0.0:18010 --settings devstack_docker'
  #   container_name: edx.devstack.studio
  #   environment:
  #     NO_PYTHON_UNINSTALL: 1
  #   image: edxops/edxapp:latest
  #   network_mode: host
  #   ports:
  #     - "18010:18010"